import type { FreightEvidenceBundle } from "@/lib/freight/types";

const percent = new Intl.NumberFormat("en-US", { style: "percent", maximumFractionDigits: 1 });

export function FreightCaseStudy({ bundle }: { bundle: FreightEvidenceBundle }) {
  const sections = ["problem", "system", "data", "leakage", "evaluation", "decisions", "history", "limitations"];
  return <section className="freight-case-study" aria-labelledby="case-study-title">
    <div className="freight-case-study__intro"><p className="eyebrow">Case study / beneath the instrument</p><h2 id="case-study-title">A freight exception system designed for review, not theater.</h2><p>The interactive surface above is the public edge of a deterministic analytical pipeline. This narrative documents where the numbers come from, what the detector can support, and where judgment still belongs.</p></div>
    <nav aria-label="Case study sections">{sections.map((section) => <a key={section} href={`#freight-${section}`}>{section}</a>)}</nav>
    <div className="freight-case-study__body">
      <article id="freight-problem"><p>01 / Problem</p><h3>Summary KPIs arrive after the operating question.</h3><p>The useful question is not simply whether freight cost rose. It is which lane, carrier scope, and time window deserves review—and what evidence makes that review proportionate.</p></article>
      <article id="freight-system"><p>02 / System</p><h3>Generation → authoritative costing → leakage-safe baselines → flags → alerts.</h3><p>Shipment exceptions and group signals keep separate evidence identities. Operational alerts deduplicate shipment exposure, group evidence, and method-family agreement before priority is calculated.</p></article>
      <article id="freight-data"><p>03 / Data</p><h3>{bundle.evaluation.overall.shipment_count.toLocaleString()} held-out evaluation shipments.</h3><p>The runtime bundle contains ranked alerts, network aggregates, three representative investigations, and a bounded sensitivity grid. Raw source files and hidden anomaly truth stay outside the portfolio.</p></article>
      <article id="freight-leakage"><p>04 / Leakage controls</p><h3>The past fits the baseline; the future only receives a score.</h3><p>Baseline statistics use the declared baseline period. Rolling signals compare current observations with strictly prior observed weeks. Cross-file run and schema identity is blocked at build time.</p></article>
      <article id="freight-evaluation"><p>05 / Evaluation</p><h3>{percent.format(bundle.evaluation.overall.recall)} recall at {percent.format(bundle.evaluation.overall.false_positive_rate)} false-positive rate.</h3><p>Precision is {percent.format(bundle.evaluation.overall.precision)}, F1 is {bundle.evaluation.overall.f1.toFixed(3)}, and the selected operating point sends {bundle.evaluation.overall.review_volume.toLocaleString()} shipments to review. The selection rule is cost-aware and calibrated before held-out evaluation.</p></article>
      <article id="freight-decisions"><p>06 / Design decisions</p><h3>Show the boundary between observed, inferred, and uncertain.</h3><p>The interface exposes score components and support, keeps decisions temporary, and offers only the three evaluation states actually exported by the analytical repository.</p></article>
      <article id="freight-history"><p>07 / Historical architecture</p><h3>Snowflake and Power BI became project history, not runtime requirements.</h3><p>The first version proved the warehouse and reporting workflow. The rebuild moved public evidence to portable Parquet/JSON artifacts so anyone can inspect the system without credentials or paid infrastructure.</p></article>
      <article id="freight-limitations"><p>08 / Limitations</p><h3>Synthetic operations make behavior testable, not universally representative.</h3><p>The fuel curve is disclosed synthetic data rather than observed EIA history. Representative lane exports are bounded, service deterioration is group evidence, and performance should not be generalized beyond this generated environment.</p><div className="freight-case-study__links"><a href="https://github.com/AbhayJuloori/freight-kpi-tracker" target="_blank" rel="noreferrer">Repository ↗</a><a href="https://github.com/AbhayJuloori/freight-kpi-tracker/tree/main/docs" target="_blank" rel="noreferrer">Methodology & model card ↗</a></div></article>
    </div>
  </section>;
}
