import type { FreightEvidenceBundle } from "@/lib/freight/types";

const percent = new Intl.NumberFormat("en-US", { style: "percent", maximumFractionDigits: 1 });

export function FreightCaseStudy({ bundle }: { bundle: FreightEvidenceBundle }) {
  const sections = ["problem", "system", "data", "leakage", "evaluation", "decisions", "history", "limitations"];
  return <section className="freight-case-study" aria-labelledby="case-study-title">
    <div className="freight-case-study__intro"><p className="eyebrow">Case study / how it works</p><h2 id="case-study-title">From a freight invoice to an explainable human decision.</h2><p>The product has one job: reduce a large shipment network to the small number of records worth reviewing, then make the reason easy to verify. Here is how the data, rules, and interface support that job.</p></div>
    <nav aria-label="Case study sections">{sections.map((section) => <a key={section} href={`#freight-${section}`}>{section}</a>)}</nav>
    <div className="freight-case-study__body">
      <article id="freight-problem"><p>01 / Problem</p><h3>A network average cannot tell an analyst which shipment to open first.</h3><p>The useful question is not simply whether freight cost rose. It is which route, carrier, shipment, and time window deserves review—and what evidence makes that review proportionate.</p></article>
      <article id="freight-system"><p>02 / System</p><h3>Reconcile the invoice, check service, add route context, then rank the review.</h3><p>Direct shipment rules decide what enters the review queue. Broader route trends provide context without automatically labeling every neighboring shipment as an exception.</p></article>
      <article id="freight-data"><p>03 / Data</p><h3>{bundle.evaluation.overall.shipment_count.toLocaleString()} later shipments tested after the rules were chosen.</h3><p>The public bundle contains {bundle.alerts.row_count} ranked reviews with focused detail for every selection, network context, and three tested sensitivity settings. Raw source files and hidden answers stay outside the portfolio.</p></article>
      <article id="freight-leakage"><p>04 / Leakage controls</p><h3>The past fits the baseline; the future only receives a score.</h3><p>Baseline statistics use the declared baseline period. Rolling signals compare current observations with strictly prior observed weeks. Cross-file run and schema identity is blocked at build time.</p></article>
      <article id="freight-evaluation"><p>05 / Evaluation</p><h3>It found {percent.format(bundle.evaluation.overall.recall)} of true exceptions with {percent.format(bundle.evaluation.overall.false_positive_rate)} false alarms.</h3><p>Precision is {percent.format(bundle.evaluation.overall.precision)}, F1 is {bundle.evaluation.overall.f1.toFixed(3)}, and the recommended setting sends {bundle.evaluation.overall.review_volume.toLocaleString()} shipments to review. The rules were selected on calibration data before these later shipments were scored.</p></article>
      <article id="freight-decisions"><p>06 / Design decisions</p><h3>Show the boundary between observed, inferred, and uncertain.</h3><p>The interface exposes score components and support, keeps decisions temporary, and offers only the three evaluation states actually exported by the analytical repository.</p></article>
      <article id="freight-history"><p>07 / Historical architecture</p><h3>Snowflake and Power BI became project history, not runtime requirements.</h3><p>The first version proved the warehouse and reporting workflow. The rebuild moved public evidence to portable Parquet/JSON artifacts so anyone can inspect the system without credentials or paid infrastructure.</p></article>
      <article id="freight-limitations"><p>08 / Limitations</p><h3>Strong synthetic results are proof of system behavior—not production performance.</h3><p>The invoices, carrier behavior, and fuel curve are disclosed synthetic data. FAF5 supplies route and mode distributions only. Real deployment would require observed invoices, contracts, carrier SLAs, and monitoring for changing operating conditions.</p><div className="freight-case-study__links"><a href="https://github.com/AbhayJuloori/freight-kpi-tracker/tree/codex/freight-v2" target="_blank" rel="noreferrer">Repository ↗</a><a href="https://github.com/AbhayJuloori/freight-kpi-tracker/tree/codex/freight-v2/docs" target="_blank" rel="noreferrer">Methodology & model card ↗</a></div></article>
    </div>
  </section>;
}
