import type { CaseStudyContent, ProjectSlug } from "@/lib/types";

const wikipulse = {
  headline: "Rank live Wikipedia edits so a patroller looks at the right ones first.",
  lede:
    "WikiPulse reads Wikimedia's public recent-change stream, scores every edit with an explainable formula, and flags likely edit wars, edit bursts, and bot bursts—through a Kafka, Spark, and Iceberg pipeline built to survive replays, late records, and schema change.",
  question: "Which live edits should a human patroller inspect first?",
  stats: [
    { value: "10 s", label: "Microbatch commit interval from Kafka to Iceberg" },
    { value: "10 min", label: "Event-time watermark bounding deduplication state" },
    { value: "1,500+", label: "Real captured edits the browser port must match exactly" },
    { value: "3", label: "Alert patterns: edit war, edit burst, bot burst" },
  ],
  statsNote:
    "System parameters, not accuracy claims. There are no ground-truth vandalism labels, so the project publishes no precision or recall.",
  sections: [
    {
      id: "question",
      heading: "A patroller cannot read the whole stream. The queue has to be ordered and explain itself.",
      body: [
        "English Wikipedia alone produces a constant flow of edits. The useful output is not a classifier verdict but a short, ranked queue where every position can be justified to the person reviewing it.",
        "The score is deliberately additive: a base of 20, plus 25 for a logged-out editor, plus 20 for a revert-like summary, plus up to 25 for size of change, minus 10 for bots. Every number on screen can be traced back to that formula.",
      ],
    },
    {
      id: "data",
      heading: "A public event stream, treated like an unreliable production source.",
      body: [
        "Edits arrive over server-sent events from Wikimedia EventStreams. The source does not participate in Kafka transactions, so a crash can replay events, and reconnecting after an outage can deliver records far behind the current watermark.",
        "Bronze keeps every raw payload keyed by Kafka coordinates for audit. Silver selects an explicit, stable contract, so additive upstream fields never break parsing.",
      ],
    },
    {
      id: "system",
      heading: "Kafka → Spark Structured Streaming → Iceberg, with idempotence at every layer.",
      body: [
        "The producer advances its stream cursor only after Kafka acknowledges a message. Spark deduplicates within a 10-minute event-time watermark, and an Iceberg MERGE on the immutable event id makes replays a no-op even after that state is gone.",
        "Alerts are recomputed for touched pages over a five-minute event-time lookback and keyed by page, minute, and type, so retries land on the same row. A FastAPI service serves an atomic JSON snapshot exported after each commit.",
      ],
    },
    {
      id: "evidence",
      heading: "Correctness is demonstrated with hard cases, not a headline metric.",
      body: [
        "Duplicate delivery, late records beyond the watermark, and an additive schema change each have a reproducible demonstration. Replaying the fixture twice leaves exactly four distinct silver rows.",
        "The TypeScript engine behind the public demo replays vectors generated by the Python parser—fixtures, edge cases, and real captured edits—and must produce identical parse, score, revert-hint, and anonymous-editor results. The suite also locks in a fix for temporary-account editors, whom an earlier pattern never recognised as logged out.",
      ],
    },
    {
      id: "interface",
      heading: "A patrol desk that runs in the visitor's browser.",
      body: [
        "The live demo opens Wikimedia's stream directly and draws every arrival on a scrolling seismograph; ticks settle when a microbatch commits. The ranked ledger draws each score as its additive parts.",
        "Visitors can stage an edit war, re-deliver the last microbatch, or send an edit an hour late, then follow each through the commit log. They can also re-weight the score and watch the queue re-rank.",
      ],
    },
    {
      id: "limitations",
      heading: "An ordering aid on a single-broker system—not a vandalism detector.",
      body: [
        "Revert hints are regex matches on edit summaries; they can be empty, translated, or misleading, so alerts describe patterns rather than confirmed bad edits. A real evaluation would derive revert labels from later revisions and compare against Wikimedia's revert-risk model at equal review volume.",
        "There is no atomic commit across bronze, silver, and alerts, and the local Hadoop catalog is not a multi-writer coordinator. The browser engine is a teaching mirror with in-memory state, not the system of record.",
      ],
    },
  ],
  links: [
    { label: "Open live patrol desk", href: "https://abhayjuloori.github.io/wikipulse/" },
    { label: "View repository", href: "https://github.com/AbhayJuloori/wikipulse" },
    { label: "Methodology & tradeoffs", href: "https://github.com/AbhayJuloori/wikipulse/blob/main/docs/methodology.md" },
  ],
} as const satisfies CaseStudyContent;

const warehouse = {
  headline: "Find the cheapest way to run a fulfillment shift without breaking the delivery promise.",
  lede:
    "A discrete-event simulation of a grocery fulfillment shift, searched for the leanest staffing and process plan that still ships 95% of orders within two hours—then re-checked on random seeds the search never saw.",
  question: "Can the center keep its promise with less labor, and what happens when volume spikes?",
  stats: [
    { value: "22%", label: "Less labor for the same SLA: 6 pickers and 3 packers instead of 8 and 4" },
    { value: "$1,985", label: "Cost per shift, down from $2,552" },
    { value: "91 min", label: "p95 cycle time under the plan, against a 120-minute promise" },
    { value: "24", label: "Never-used seeds every reported number is averaged over" },
  ],
  statsNote:
    "All figures are simulated. Customer behavior comes from public Instacart orders; floor layout, task times, wages, and the SLA are stated assumptions.",
  sections: [
    {
      id: "question",
      heading: "A center ships about 320 orders a shift with 8 pickers and 4 packers. Is that the right crew?",
      body: [
        "The promise is that 95% of orders leave within two hours. Three decisions follow: whether the promise holds with fewer people, how many people a demand spike needs, and which process changes are worth paying for.",
      ],
    },
    {
      id: "data",
      heading: "Real customer behavior, explicitly assumed operations.",
      body: [
        "Public Instacart orders (3.4M orders, 32M lines) supply the hour-of-day arrival shape, basket sizes, item popularity, and aisle co-purchase groups. Two disjoint hash samples keep the data that defines affinity slotting separate from the data that generates baskets.",
        "An early basket generator gave affinity slotting a circular advantage. That run was discarded and recorded, not quietly fixed.",
      ],
    },
    {
      id: "system",
      heading: "Simulate the shift, search the levers, then refuse to trust the search.",
      body: [
        "A SimPy model runs waves, batch picking across a 12-zone floor, packing, and shipping, with overtime charged until the last order leaves. Optuna searches pickers, packers, batch size, wave interval, and slotting.",
        "A plan is accepted only if the one-sided 95% bootstrap bound on late orders stays at or below 5%—first on verification seeds, then again on seeds never used for selection. Without that second stage, a plan picked at a 3.1% bound replayed at 6.4% and would have missed the promise.",
      ],
    },
    {
      id: "evidence",
      heading: "Process matters more than headcount.",
      body: [
        "Single-order picking costs 2.35× more picker time per order than six-order batches, and late orders pass 24% when batches drop below four. In the recommended plan packers run at 81% utilization, so packing becomes the next bottleneck: losing one packer pushes late orders to 64%.",
        "Today's crew absorbs +40% volume but fails at +50%; with retuned batches and waves, the same 12 people meet the promise at +50%. Re-slotting the floor lands within 0.3% of random slotting while batch-picking, so it is not worth funding yet.",
        "A LightGBM surrogate reached 0.94–0.98 held-out R², but its breach error of ±4.4 points around a 5% limit led it to a knife-edge plan. The plain simulator search found a cheaper plan in 9.8 seconds, so the surrogate is kept only for instant what-if answers.",
      ],
    },
    {
      id: "interface",
      heading: "Ask a what-if in plain English; every number comes from the model.",
      body: [
        "Streamlit and FastAPI turn questions like “what if Monday volume rises 30% and we cut two pickers?” into a validated scenario, through a rules parser or an LLM tool call. The answer's numbers come from the simulator output, never from generated text.",
        "The project page walks through the whole story in three minutes, with a plain-English and technical toggle.",
      ],
    },
    {
      id: "limitations",
      heading: "How the levers interact under stated assumptions—not a savings estimate for a real site.",
      body: [
        "Wages, walk and pick times, and the floor are assumptions, and the 1,000-SKU, 12-zone layout is coarse enough to understate slotting. The search is a verified shortlist, not a proof of a global optimum, and bootstrap bounds cover seed noise only.",
        "Calibrating against real warehouse event logs is the next step. Live LLM parsing accuracy is unmeasured; the rules parser's 68-of-68 result is in-sample.",
      ],
    },
  ],
  links: [
    { label: "Open project page", href: "https://abhayjuloori.github.io/warehouse-fulfillment-digital-twin/" },
    { label: "View repository", href: "https://github.com/AbhayJuloori/warehouse-fulfillment-digital-twin" },
    { label: "Experiment log", href: "https://github.com/AbhayJuloori/warehouse-fulfillment-digital-twin/blob/main/docs/experiment-log.md" },
  ],
} as const satisfies CaseStudyContent;

const fraud = {
  headline: "Graph features sound like the obvious fraud upgrade. Here they earned nothing—so they didn't ship.",
  lede:
    "A PaySim fraud experiment with time-safe transaction-graph features, a promotion gate the graph model had to clear, an MLflow-registered champion served with TreeSHAP reasons, and drift monitoring that queues retraining.",
  question: "Do transaction-graph features improve fraud detection enough to justify their complexity?",
  stats: [
    { value: "+0.0004", label: "Graph lift in test PR-AUC on the confirmation cohort" },
    { value: "0.01", label: "Validation lift required to promote the graph model" },
    { value: "0.9785", label: "Test PR-AUC of the simpler transaction-only champion" },
    { value: "1.59M", label: "Rows in the time-split confirmation cohort" },
  ],
  statsNote:
    "PaySim is synthetic and unusually separable. High PR-AUC here does not establish a useful live fraud policy.",
  sections: [
    {
      id: "question",
      heading: "Added complexity has to pay for itself before it reaches production.",
      body: [
        "Graph features—degrees, PageRank, shared counterparties, ring and component flags, neighborhood fraud rates—are a common fraud-detection upgrade. The question was whether they beat a well-built transaction-only model by enough to be worth maintaining.",
        "After a first cohort showed a tiny validation gain and a test loss, the graph model was required to beat the baseline by 0.01 absolute validation PR-AUC. A disjoint second cohort is the published confirmation.",
      ],
    },
    {
      id: "data",
      heading: "A uniform, label-independent cohort with a strict time split.",
      body: [
        "The confirmation run draws 25% of the 6.36M-row PaySim dataset, independent of labels, then splits by whole time step: 955,801 training rows, 323,099 validation, and 312,885 later test rows.",
        "Post-transaction balances and the dataset's own fraud flag are excluded. The scoring API accepts only fields known before a transaction happens.",
      ],
    },
    {
      id: "system",
      heading: "Each step's graph is built before its labels can leak in.",
      body: [
        "A temporal NetworkX graph uses only earlier-step edges; training labels update neighborhood fraud rates after each step, and validation and test labels never do. Logistic regression, transaction-only XGBoost, and graph XGBoost share the same cohort and split.",
        "The champion is chosen on validation only, registered in MLflow, and served by FastAPI, which returns a probability, model version, and the three largest signed TreeSHAP contributions. Evidently and a KS check compare later data against validation and queue a retrain that waits for mature labels.",
      ],
    },
    {
      id: "evidence",
      heading: "No demonstrated graph lift—and a clear reason why.",
      body: [
        "Transaction-only XGBoost reached 0.9785 test PR-AUC and graph XGBoost 0.9789. On validation the graph model was slightly worse, and an earlier cohort showed −0.0038. The gate kept the simpler model.",
        "99.85% of senders appear exactly once, so a graph has almost no repeat actors to learn from: held-out sender degree is non-zero 0.1% of the time. Meanwhile 97.8% of fraud drains the full origin balance, making amount-to-balance about six times more important than any other feature.",
        "Under a simulated 3× amount shift, alert volume per 100k transfers rises from 1,415 to 5,737—the monitoring cost an investigator team would feel first.",
      ],
    },
    {
      id: "interface",
      heading: "An evidence page, a scoring API, and a live monitor.",
      body: [
        "The project page walks through the experiment with interactive D3 charts fed by the committed aggregate results. Locally, a Streamlit monitor shows drift status, a hand scorer with reason codes, and model evidence; the API's documentation is served alongside it.",
      ],
    },
    {
      id: "limitations",
      heading: "Synthetic data, few validation frauds, and a generous operating point.",
      body: [
        "Validation has only 208 fraud cases, and graph lift changed sign across cohorts. The 1% false-positive threshold caught every test fraud, but only 24% of alerts were fraud.",
        "Daily drift checks on unshifted data fired on 5 of 17 days, so a real monitor would need volume guards. Real transaction networks with repeat actors could reward graph features in a way PaySim cannot test.",
      ],
    },
  ],
  links: [
    { label: "Open project page", href: "https://abhayjuloori.github.io/graph-aware-fraud-detection/" },
    { label: "View repository", href: "https://github.com/AbhayJuloori/graph-aware-fraud-detection" },
    { label: "Methodology", href: "https://github.com/AbhayJuloori/graph-aware-fraud-detection/blob/main/docs/methodology.md" },
  ],
} as const satisfies CaseStudyContent;

const caseStudies: Partial<Record<ProjectSlug, CaseStudyContent>> = {
  wikipulse,
  "warehouse-digital-twin": warehouse,
  "graph-fraud-detection": fraud,
};

export function getCaseStudy(slug: ProjectSlug): CaseStudyContent | undefined {
  return caseStudies[slug];
}
